= Reporting Business Process

include::parties.adoc[]

== End-User Reporting Process

NOTE: Consolidated Diagram and process overview to be added

=== Data Gathering
//NOTE: Elaboration on Business Requirements (see Philip's excel file) on Data Gathering

* Reporting Period

- The "reporting period" starts with the first day of every month at 00:00:00 UTC (inclusive) and ends with the last day of said month at 23:59:59 UTC (inclusive).

- If a Service Provider initiates its Peppol activities during a reporting period, this particular reporting period starts for this Service Provider at the initiation point in time.

- If a Service Provider ends its Peppol activities during a reporting period, this particular reporting period ends for this Service Provider at the ending point in time. The report must be send anyway.

* Data

- Only Service Providers offering the exchange of Dataset Types must fill out and transmit an End User Report.

- Only Data for production must be sent.

- Only End Users that were the source of a dataset send via Peppol (C1) or the receiver of a dataset sent via Peppol (C4) within the reporting period must be part of the End User Report

- A legal identifier of the particular Intermediary must be provided

- The type of the legal identifier of the particular Intermediary must be provided

- The country of the particular Intermediary must be provided

- The territory of the particular Intermediary may be provided

- A legal identifier of the particular End User must be provided
- The type of the legal identifier of the particular End User must be provided
- The country of the particular End User must be provided
- The territory of the particular End User may be provided
- All dataset types the particular End User was sending in the reporting period must be provided
- All dataset types the particular End User was receiving in the reporting period must be provided
- All Peppol participant identifiers used by the particular End User must be provided
- Zero, one or more Intermediaries may be provided per particular End User






=== Data Aggregation

// NOTE: Elaboration on Business Requirements (see Philip's excel file) on Data Aggregation

* Data





=== Data Transmission
NOTE: Elaboration on Business Requirements (see Philip's excel file) on Data Transmission

* Frequency

- An End User Report must be transmitted once per month ("reporting period")

- An End User Report must be transmitted within 10 days (inclusive) after the end of the previous reporting period

- The report must be transmitted, even if no Peppol transactions happened

- In case the report of one Service Provider is received multiple times, only the latest received document will be evaluated

* Data

- Only End User Reports on the Production stage must be transmitted

- Each End User must not be contained more than once in a report

- The data of each End User must be reported separately

- The begin and end date of the reporting period must be part of the transmission data

- An identifier uniquely identifying the reporting Service Provider must be part of the transmission data

* Network

- End User Reports must be transmitted via the Peppol eDelivery Network

- End User Reports must only be transmitted to the Peppol Participant iD Indicated in chapter 8. BIS Identifier

- Only OpenPeppol is allowed to receive End User Reports

