= Reporting Business Process

== Parties and Roles

//NOTE: add the main parties of the *Business Process*. The party is the service provider on the role of reporter and the Peppol OO as the report receiver
:leveloffset: +1
The following roles may be specified. 
//The same actor may play more than one role depending on the handling routine.

//Further details on the roles/actors can be found in <<roles>>.

== Service Provider (SP) 

Service Provider  is mandatory information and provided in element 

`eur:EndUserReport / eur:Header / eur:ReporterID`

.EUR example of Service Provider information
[source, xml, indent=0]
----
    <ReporterID schemeID="CertSubjectCN">POP000360</ReporterID>
----


. Service Provider  schemeID (IBT-060-1), mandatory, the identification scheme identifier shall be chosen from the entries of the list published by the https://www.iso.org/standard/25773.html[ISO/IEC 6523] maintenance agency.
. ReporterID (IBT-060) the value of the Peppol AP Certificate Subject CN (Common Name) to uniquely identify the Service Provider that is providing the data.

SPs will:

* Collect relevant data, taking care with the accuracy and validity of this data.
* Report this data in accordance to this document. This interface allows for a standardized and structured dataset from where the Peppol Coordinating Authority can automate processing and aggregation of the data upon receival in the Peppol Reporting Platform.
* Ensure all data for a month is reported within 10 calendar days following the end of the month.
* Transmit the Peppol End User Report BIS to the Peppol Coordinating Authority in accordance with this specification.

== OpenPeppol Operating Office (OO)

operating Office is mandatory information and provided in element ` ?????`

.EUR example of Operating Office information
[source, xml, indent=0]
----
<eur:ProfileID>urn:fdc:peppol.eu:oo:bis:reporting:1</eur:ProfileID> 
----

NOTE: to be corrected

. Operating Office identifier  (IBT-002), identifies the business process context in which the transaction appears, to enable the receiver to process the document in an appropriate way.
//<2> Buyer identifier (ibt-046), if used, the identification scheme identifier shall be chosen from the entries of the list published by the ISO/IEC 6523 maintenance agency.

The OpenPeppol Operating Office (OO) will:

* Automatically check which providers have not submitted their End User Report. This check will be triggered automatically.
* Prompt any SPs that have not submitted the End User Report.
* Prompting will be done by email and not by eDelivery
* Define that in due time is supposed to be 5 days, giving it a total of 15 days
* Prompt the PA of the SP if a SP fails to submit the End User Report in due time after reminders are sent. The PA of the SP will be informed to handle this as a non-compliance issue.
* Failure by SPs to provide full and complete reports can be managed in accordance with the https://openpeppol.atlassian.net/wiki/spaces/AF/pages/2756771841/New+Peppol+Agreements+and+accompanying+documents#B3.-Operational-Procedures[Non-compliance Operational Procedure].

:leveloffset: -1

== End-User Reporting Process

NOTE: Consolidated Diagram and process overview to be added

=== Data Gathering
//NOTE: Elaboration on Business Requirements (see Philip's excel file) on Data Gathering

* Reporting Period

- The "reporting period" starts with the first day of every month at 00:00:00 UTC (inclusive) and ends with the last day of said month at 23:59:59 UTC (inclusive).

- If a Service Provider initiates its Peppol activities during a reporting period, this particular reporting period starts for this Service Provider at the initiation point in time.

- If a Service Provider ends its Peppol activities during a reporting period, this particular reporting period ends for this Service Provider at the ending point in time. The report must be send anyway.

* Data

- Only Service Providers offering the exchange of Dataset Types must fill out and transmit an End User Report.

- Only Data for production must be sent.

- Only End Users that were the source of a dataset send via Peppol (C1) or the receiver of a dataset sent via Peppol (C4) within the reporting period must be part of the End User Report

- A legal identifier of the particular Intermediary must be provided

- The type of the legal identifier of the particular Intermediary must be provided

- The country of the particular Intermediary must be provided

- The territory of the particular Intermediary may be provided

- A legal identifier of the particular End User must be provided
- The type of the legal identifier of the particular End User must be provided
- The country of the particular End User must be provided
- The territory of the particular End User may be provided
- All dataset types the particular End User was sending in the reporting period must be provided
- All dataset types the particular End User was receiving in the reporting period must be provided
- All Peppol participant identifiers used by the particular End User must be provided
- Zero, one or more Intermediaries may be provided per particular End User






=== Data Aggregation

// NOTE: Elaboration on Business Requirements (see Philip's excel file) on Data Aggregation

* Data





=== Data Transmission
NOTE: Elaboration on Business Requirements (see Philip's excel file) on Data Transmission

* Frequency

- An End User Report must be transmitted once per month ("reporting period")

- An End User Report must be transmitted within 10 days (inclusive) after the end of the previous reporting period

- The report must be transmitted, even if no Peppol transactions happened

- In case the report of one Service Provider is received multiple times, only the latest received document will be evaluated

* Data

- Only End User Reports on the Production stage must be transmitted

- Each End User must not be contained more than once in a report

- The data of each End User must be reported separately

- The begin and end date of the reporting period must be part of the transmission data

- An identifier uniquely identifying the reporting Service Provider must be part of the transmission data

* Network

- End User Reports must be transmitted via the Peppol eDelivery Network

- End User Reports must only be transmitted to the Peppol Participant iD Indicated in chapter 8. BIS Identifier

- Only OpenPeppol is allowed to receive End User Reports

