= Parties and Roles

The following roles may be specified. 

== Service Provider (SP) 

The reporting Service Provider is mandatory information in each End User Report.
It must be in this element: 

[source, xml, indent=0]
----
eur:EndUserReport/eur:Header/eur:ReporterID
----

1. The attribute `schemeID` (IBT-005) is mandatory and contains the 
  scheme identifier that defines the syntax and semantic of the content
  of the `ReporterID` element. The matching code list is <<codelist-repidscheme>>.
2. The element `ReporterID` (IBT-004) needs to contain the value of the 
  Peppol AP Certificate Subject CN (Common Name) to uniquely identify the 
  Service Provider that is providing the data.

.Example of Service Provider information
[source, xml, indent=0]
----
<eur:ReporterID schemeID="CertSubjectCN">POP000360</eur:ReporterID>
----

NOTE: TODO Shall we remove the following paragraph? 

SPs will:

* Collect relevant data, taking care of the accuracy and validity 
  of this data.
* Report this data in accordance to this document in a standardized and structured dataset. 
* Ensure all data for a month is reported within 10 calendar days following the end of the month.
* Transmit the Peppol End User Report BIS document to the Peppol Coordinating Authority in accordance with this specification.

== OpenPeppol Operating Office (OO)

Operating Office is the sole receiver of all End User Reports
sent by Service Providers.

// TODO is this okay like this?
NOTE: The Participant Identifier under which OO will receive the End User Reports is not part of this document.

OO will:

* Automatically check which providers have not submitted their End User Report. This check will be triggered automatically.
* Prompt any SPs that have not submitted the End User Report.
* Prompting will be done by email and not by eDelivery.
* Prompt the PA of the SP if an SP fails to provide full and complete reports. The PA of the SP will be informed to handle this as a non-compliance issue
