= Subtotals

Each Transaction Statistics Report contains different subtotals.
Each subtotal represents a different view on the transaction statistics data.

The technical representation of the subtotals was designed in a generic way,
  to allow for future extension without modifying the underlying schema.
  Each `Subtotal` element therefore requires a `@type` attribute that defines
  the type of the subtotal. The value range is defined by the
  <<codelist-subtotaltype>> code list.
  
All values in this subchapter are case-sensitive, except stated otherwise.

== Subtotal per Transport Protocol

This subtotal is identified by the `@type` attribute having the value `PerTP`.

* This subtotal requires one `Key` element with a Meta Scheme ID of `TP`
  (Transport Protocol).
The `schemeID` attribute of this `Key` element MUST have the value `Peppol`.
The value of the `Key` element MUST be the transport protocol identifier
  according to the <<codelist-tp>> code list.
  
Each Transport Protocol MUST be reported in a separate `Subtotal` element.

The sum all incoming amounts per Transport Protocol MUST match the total
  incoming amount. 

The sum all outgoing amounts per Transport Protocol MUST match the total
  outgoing amount. 

.Example of a subtotal per Transport Protocol:
[source, xml]
----
include::./snippet/snippet-1.xml[tags=SubtotalPerTP]
----

== Subtotal per Service Provider and Dataset Type

This subtotal is identified by the `@type` attribute having the value `PerSP-DT`.

* This subtotal requires one `Key` element with a Meta Scheme ID of `SP`
  (Service Provider).
The `schemeID` attribute of this `Key` element MUST have a value according
  to the <<codelist-repidscheme>> code list.
The value of the `Key` element MUST follow the rules of the chosen scheme.
* This subtotal requires one `Key` element with a Meta Scheme ID of `DT`
  (Dataset Type).
The `schemeID` attribute of this `Key` element MUST be the Document Type
  Identifier Scheme of the exchanged Dataset (usually `busdox-docid-qns`).
The value of the `Key` element MUST be the Dataset Type (Document Type)
  Identifier value of the exchanged Dataset.
  
Each combination of Service Provider and Dataset Type MUST be
  reported in a separate `Subtotal` element.

The sum all incoming amounts per Service Provider and Dataset Type MUST
   match the total incoming amount.

The sum all outgoing amounts per Service Provider and Dataset Type MUST 
  match the total outgoing amount.

NOTE: For outgoing messages, only the receiving Service Provider needs
  to be counted. For incoming messages, only the sending Service Provider needs
  to be counted. The other side must always be the reporting Service Provider
  that is already part of the header data. 

.Example of a subtotal per Service Provider and Dataset Type:
[source, xml]
----
include::./snippet/snippet-1.xml[tags=SubtotalPerSP-DT]
----


== Subtotal per Service Provider, Dataset Type and Country Codes

This subtotal is identified by the `@type` attribute having the value `PerSP-DT-CC`.

* This subtotal requires one `Key` element with a Meta Scheme ID of `SP`
  (Service Provider).
The `schemeID` attribute of this `Key` element MUST have a value according
  to the <<codelist-repidscheme>> code list.
The value of the `Key` element MUST follow the rules of the chosen scheme.
* This subtotal requires one `Key` element with a Meta Scheme ID of `DT`
  (Dataset Type).
The `schemeID` attribute of this `Key` element MUST be the Document Type
  Identifier Scheme of the exchanged Dataset (usually `busdox-docid-qns`).
The value of the `Key` element MUST be the Dataset Type (Document Type)
  Identifier value of the exchanged Dataset.
* This subtotal requires one `Key` element with a Meta Scheme ID of `CC`
  (Country Code) and the `schemeID` attribute of `SenderCountry`.
The value of the `Key` element MUST have a value according to the
  <<codelist-countrycode>> code list.
* This subtotal requires one `Key` element with a Meta Scheme ID of `CC`
  (Country Code) and the `schemeID` attribute of `ReceiverCountry`.
The value of the `Key` element MUST have a value according to the
  <<codelist-countrycode>> code list.
  
Each combination of Service Provider, Dataset Type, Sender Country 
  and Receiver Country MUST be reported in a separate `Subtotal` element.

The sum all incoming amounts per Service Provider and Dataset Type MUST
   match the total incoming amount. 

The sum all outgoing amounts per Service Provider and Dataset Type MUST 
  match the total outgoing amount. 

NOTE: For outgoing messages, only the receiving Service Provider needs
  to be counted. For incoming messages, only the sending Service Provider needs
  to be counted. The other side must always be the reporting Service Provider
  that is already part of the header data. 

.Example of a subtotal per Service Provider, Dataset Type and Country Codes:
[source, xml]
----
include::./snippet/snippet-1.xml[tags=SubtotalPerSP-DT-CC]
----
