= Transaction statistics Reporting Process

// TODO
The following diagram provides an overview of the key steps when Service Providers are reporting monthly Transaction Statistics. The diagram is a general representation of the process flow; some steps can be undertaken in parallel and do not need to be completed in strict order.

NOTE: Consolidated Diagram and process overview to be added

== Data Gathering

//NOTE: Elaboration on Business Requirements (see Philip's excel file) on Data Gathering  To be corrected

* Reporting Period
** The Reporting Period starts with the first day of every month at 
   00:00:00 UTC (inclusive) and ends with the last day of said month
   at 23:59:59 UTC (inclusive).

* Data
** Only Service Providers offering the exchange of Dataset Types must
   gather this data and transmit a Transaction Statistics Report.
** Only data for production MUST be sent.
** According to the Internal Regulations, chapter 4.4, the following 
   information elements need to be gathered for each exchanged Dataset:
    1. Timing of the exchange
    2. Direction of the exchange (incoming or outgoing)
    3. Sending Peppol Service Provider
    4. Receiving Peppol Service Provider
    5. Peppol Dataset Type (Document Type ID)
    6. Transport protocol used
    7. Country of sender
    8. Country of receiver
** Only Dataset exchanges that resulted in a positive transport level
   acknowledgments (like AS4 Receipts) MUST be included in the Transaction
   Statistics Report. Transmissions that failed on a network or protocol
   level MUST NOT to be considered for the report.
*** End User Reports MUST NOT be counted for a Transaction Statistics Report
*** Transaction Statistics Reports themselves MUST NOT be counted for a
    Transaction Statistics Report
    


== Data Aggregation

Before the Transaction Statistics Report data is transmitted to OpenPeppol
  it needs to be aggregated. The aggregation can be performed on any of the
  above mentioned source fields defined by the Internal Regulations.
  
The following aggregations MUST be provided to be compliant to this specification:

* Transport Protocol only
* Service Provider and Dataset Type
* Service Provider, Dataset Type, Sender Country and Receiver Country 

== Data Transmission

// TODO needed
// Elaboration on Business Requirements (see Philip's excel file) on Data Transmission

* Frequency
** A Transaction Statistics Report MUST be transmitted once per month 
   (Reporting Period)
** A Transaction Statistics Report MUST be transmitted within 10 calendar days 
   (inclusive) after the end of the previous Reporting Period
** The Transaction Statistics Report MUST be transmitted, even if no other Peppol
   exchange happened in the Reporting Period
** In case the Transaction Statistics Report of one Service Provider is received
   multiple times for one Reporting Period, only the latest received 
   document will be processed.
** Transaction Statistics Reports received after the deadline WILL NOT be processed.   

* Data
** Only Transaction Statistics Reports on the Production stage MUST be transmitted
** Each Transaction Statistics MUST NOT occur more than once in a 
   Transaction Statistics Report
** The data of each Transaction Statistics must be reported in the designated
   elements
** The Reporting Period MUST be part of the Transaction Statistics Report
** An identifier uniquely identifying the reporting Service Provider 
   MUST be part of the Transaction Statistics Report

* Network
** Transaction Statistics Reports must be transmitted via the Peppol eDelivery
   Network
** Only OpenPeppol is allowed to receive Transaction Statistics Reports directly
