= Subset Information

An End User Statistics Report contains information about subsets of End Users.
Each subset represents a different view on the End User Statistics data.

The technical representation of the subsets was designed in a generic way,
  to allow for future extension without modifying the underlying schema.
  Each `Subset` element therefore requires a `@type` attribute that defines
  the type of the subset. The value range is defined by the
  <<codelist-subsettype>> code list.
  
== Subset per Dataset Type and Process ID

This subset is identified by the `@type` attribute having the value `PerDT-PR`.

* This subset requires one `Key` element with a Meta Scheme ID of `DT` (Dataset Type).
The `@schemeID` attribute of this `Key` element MUST be the Document Type Identifier Scheme
of the exchanged Dataset (usually `busdox-docid-qns`). The value of the `Key` element MUST be
the Dataset Type (Document Type) Identifier value of the exchanged dataset.

* This subset requires one `Key` element with Meta Scheme ID of `PR` (Process ID).
The `schemeID` attribute of this `Key` element MUST be the Process Identifier
Scheme of the process (Peppol profile) used (usually `cenbii-procid-ubl`).
The value of the `Key` element MUST be the Process ID value of the process
(Peppol profile) used.

Each distinct combination of the Dataset Type and Process ID MUST be reported in a separate
`Subset` element.


The element `eusr:Subset/eusr:SendingEndUsers` contains the number of distinct 
  end users that have sent datasets using this combination of the Dataset Type and Process ID. 
  Only values &ge; 0 are allowed.

The element `eusr:Subset/eusr:ReceivingEndUsers` contains the number of distinct 
  end users that have received datasets using this combination of the Dataset Type and Process ID. 
  Only values &ge; 0 are allowed.

The element `eusr:Subset/eusr:SendingOrReceivingEndUsers` contains the number of distinct 
  end users that have either sent or received datasets using this combination of the Dataset Type and Process ID. 
  Only values &ge; 0 are allowed.


.Example of a subset per Dataset Type and Process ID:
[source, xml]
----
include::./snippet/snippet-1.xml[tags=SubsetPerDT-PR]
----

== Subset per Dataset Type, Process ID, Sender Country and Receiver Country

This subset is identified by the `@type` attribute having the value `PerDT-PR-CC`.

* This subset requires one `Key` element with a Meta Scheme ID of `DT` (Dataset Type).
The `@schemeID` attribute of this `Key` element MUST be the Document Type Identifier Scheme
of the exchanged Dataset (usually `busdox-docid-qns`). The value of the `Key` element MUST be
the Dataset Type (Document Type) Identifier value of the exchanged dataset.

* This subset requires one `Key` element with Meta Scheme ID of `PR` (Process ID).
The `schemeID` attribute of this `Key` element MUST be the Process Identifier
Scheme of the process (Peppol profile) used (usually `cenbii-procid-ubl`).
The value of the `Key` element MUST be the Process ID value of the process
(Peppol profile) used.

* This subset requires one `Key` element with a Meta Scheme ID of `CC`
  (Country Code) and the `schemeID` attribute of `SenderCountry`.
  The value of the `Key` element MUST have a value according to the
  <<codelist-countrycode>> code list.
  
* This subset requires one `Key` element with a Meta Scheme ID of `CC`
  (Country Code) and the `schemeID` attribute of `ReceiverCountry`.
  The value of the `Key` element MUST have a value according to the
  <<codelist-countrycode>> code list.


Each distinct combination of the Dataset Type, Process ID, Sender Country and Receiver Country 
  MUST be reported in a separate `Subset` element.


The element `eusr:Subset/eusr:SendingEndUsers` contains the number of distinct 
  end users that have sent datasets using this combination of the Dataset Type, Process ID, Sender Country and Receiver Country. 
  Only values &ge; 0 are allowed.

The element `eusr:Subset/eusr:ReceivingEndUsers` contains the number of distinct 
  end users that have received datasets using this combination of the Dataset Type, Process ID, Sender Country and Receiver Country. 
  Only values &ge; 0 are allowed.

The element `eusr:Subset/eusr:SendingOrReceivingEndUsers` contains the number of distinct 
  end users that have either sent or received datasets using this combination of the Dataset Type, Process ID, Sender Country and Receiver Country. 
  Only values &ge; 0 are allowed.


.Example of a subset per Dataset Type, Process ID, Sender Country and Receiver Country:
[source, xml]
----
include::./snippet/snippet-1.xml[tags=SubsetPerDT-PR-CC]
----
