= Parties and Roles

The following Parties are involved in the creation and submission of an Transaction Statistics Report.

== Service Provider (SP) 

The reporting Service Provider is mandatory information in each Transaction Statistics Report.

Each SP will:

* Collect relevant data, taking care of the accuracy and validity of this data.
* Report this data in accordance to this specification in a standardized and structured dataset. 
* Ensure all data for a Reporting Period is reported within the Statistics Report Submitting Period following the end of the Reporting Period.
  Note: the Reporting Period is defined by OpenPeppol in a separate document.
* Transmit the Peppol Transaction Statistics Report document to the PCA in accordance with this specification.

== OpenPeppol Operating Office (OO)

OO will:

* Automatically check which providers have not submitted their Transaction Statistics Report. This check will be triggered automatically.
* Prompt any SPs that have not submitted the Transaction Statistics Report.
* Prompting will be done by email and not by eDelivery.
* Prompt the PA of the SP if an SP fails to provide full and complete reports. The PA of the SP will be informed to handle this as a non-compliance issue
