= End User

Defines the data for a single End User.
The element `EndUser` and its child elements MUST be provided for every End User to be reported. 

== End User/Legal ID
The element `EndUser/LegalID` MUST contain the Legal identifier of the End User in 
the jurisdiction within which it is legally based, 
as well as the legal identifier Type (e.g., VAT number, company registration number).

a. The legal identifier has to be active, in jurisdictions where such distinction exists.
b. In case of End Users that are public organisations and where legal identifiers as 
    such do not exist, other officially issued codes are acceptable.
    
The attribute `schemeID` does not follow a specific code list.
If possible, the values of the Peppol Participant Identifier Scheme 
code list SHOULD be used (like "9914" for an Austrian VAT number).

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=LegalID]
----


== End User/Legal Name

The element `EndUser/LegalName` MUST contain the Legal name of the End User, 
in the jurisdiction within which it is legally based.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=LegalName]
----

== End User/Country

The element `EndUser/Country` MUST contain the country code of the End User's legal address only.
The values in this element MUST be part of the <<codelist-countrycode>> code list.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=Country]
----

== End User/Territory

The element `EndUser/Territory` is optional. 
If it is present, it MUST contain the Territory of the End User's legal address.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=Territory]
----

== End User/Sending Dataset Type

For every unique Dataset Type ID (Document Type ID) this End User has sent in the reporting period,
one `EndUser/SendingDatasetTypeID` element MUST be provided.
The `schemeID` attribute MUST contain the scheme identifier of the respective Dataset Type ID.

NOTE: The number of exchanged Datasets is not part of this report, it is part of the Transaction Statistics Report.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=SendingDatasets]
----

== End User/Receiving Dataset Type

For every unique Dataset Type ID (Document Type ID) this End User has received in the reporting period,
one `EndUser/ReceivingDatasetTypeID` element MUST be provided.
The `schemeID` attribute MUST contain the scheme identifier of the respective Dataset Type ID.

NOTE: The number of exchanged Datasets is not part of this report, it is part of the Transaction Statistics Report.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=ReceivingDatasets]
----

== End User/Participant ID

The element `EndUser/ParticipantID` MUST contain the Participant ID.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=ParticipantID]
----

== End User/Intermediary

The element `EndUser/Intermediary` MUST contain the Intermediary information.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=Intermediary]
----

== EndUser/Intermediary/LegalID

The element `LegalID` MUST contain the Legal Identifier of the intermediary organisation.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=IntermediaryLegalID]
----


== EndUser/Intermediary/LegalName

The element `LegalName` MUST contain the Legal Name of the reporting organisation.
Legal name of the End User, in the jurisdiction within which it is legally based.
.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=IntermediaryLegalName]
----

== EndUser/Intermediary/Country

The element `Country` MUST contain the country code of the intermediary's legal address only.
The values in this element MUST be part of the <<codelist-countrycode>> code list.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=IntermediaryCountry]
----

== EndUser/Intermediary/Territory

The element `Territory` is optional. 
If it is present, it MUST contain the Territory of the intermediary's legal address.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=IntermediaryTerritory]
----
