= EndUser
Defines the data for a single end user.

== EndUser/Legal ID
The element `LegalID` MUST contain the Legal Identifier of the reporting organisation.
Legal identifier of the End User in the jurisdiction within which it is legally based, 
and legal identifier Type (e.g., VAT number, company registration number).
a. The legal identifier has to be active, in jurisdictions when such distinction exists.
 b. In case of End Users that are public organisations and where legal identifiers as 
    such do not exist, other officially issued codes are acceptable.
    The schemeID does not follow a code list. If possible, the values of the Peppol
    Participant Identifier Scheme Code List SHOULD be used (like "9914" for an
    Austrian VAT number).

.Example:
[source, xml, indent=0]
----
include::./snippet//snippet-2.xml[tags=LegalID]
----


== EndUser/Legal Name
The element `LegalName` MUST contain the Legal Name of the reporting organisation.
Legal name of the End User, in the jurisdiction within which it is legally based.
.Example:
[source, xml, indent=0]
----
include::./snippet//snippet-2.xml[tags=LegalName]
----

== EndUser/Country
The element `Country` MUST contain the country of the End User's legal address only.
This type is used to represent link:/eur/end_user_reporting/codelist/ISO3166/index.html[ISO-3166 country codes] in Alpha-2 Mode.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-2.xml[tags=Country]
----

== EndUser/Territory
The element `Territory` MUST contain the Territory of the End User's legal address.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-2.xml[tags=Country]
----

== EndUser/ReceivingDatasets
The element `ReceivingDatasets` MUST contain the list of the datasets included in the report.
 End User's capability to send Peppol Dataset Types (Document Type ID).
.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-2.xml[tags=ReceivingDatasets]
----

== EndUser/SendingDatasets
The element `SendingDatasets` MUST contain the list of the datasets included in the report.
 End User's capability to send Peppol Dataset Types (Document Type ID).
.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-2.xml[tags=SendingDatasets]
----

== EndUser/ParticipantID
The element `ParticipantID` MUST contain the Participant ID.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-2.xml[tags=ParticipantID]
----

== EndUser/Intermediary
The element `Intermediary` .
 Must contain the Intermediary informations
.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-2.xml[tags=Intermediary]
----

== EndUser/Intermediary/Legal ID
The element `LegalID` MUST contain the Legal Identifier of the intermediary organisation.

.Example:
[source, xml, indent=0]
----
include::./snippet//snippet-2.xml[tags=IntermediaryLegalID]
----


== EndUser/Intermediary.\/Legal Name
The element `LegalName` MUST contain the Legal Name of the reporting organisation.
Legal name of the End User, in the jurisdiction within which it is legally based.
.Example:
[source, xml, indent=0]
----
include::./snippet//snippet-2.xml[tags=IntermediaryLegalName]
----

== EndUser/Intermediary/Country
The element `Country` MUST contain the country of the End User's legal address only.
This type is used to represent ISO-3166 country codes in Alpha-2 Mode.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-2.xml[tags=IntermediaryCountry]
----