= End User

Defines the data for a single End User.
The element `EndUser` and its child elements MUST be provided for every End User to be reported. 

.Example of a regular End User:
[source, xml]
----
include::./snippet/snippet-1.xml[tags=EndUserDefault]
----

.Example of a End User with all optional elements:
[source, xml]
----
include::./snippet/snippet-1.xml[tags=EndUserFull]
----

== End User/Legal ID
The element `EndUser/LegalID` MUST contain the Legal identifier of the End User in 
the jurisdiction within which it is legally based, 
as well as the legal identifier Type (e.g., VAT number, company registration number).

a. The legal identifier has to be active, in jurisdictions where such distinction exists.
b. In case of End Users that are public organisations and where legal identifiers as 
    such do not exist, other officially issued codes are acceptable.
    
The attribute `schemeID` does not follow a specific code list.
If possible, the values of the Peppol Participant Identifier Scheme 
code list SHOULD be used (like "9914" for an Austrian VAT number).

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=LegalID]
----


== End User/Legal Name

The element `EndUser/LegalName` MUST contain the Legal name of the End User, 
in the jurisdiction within which it is legally based.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=LegalName]
----

== End User/Country

The element `EndUser/Country` MUST contain the country code of the End User's legal address only.
The values in this element MUST be part of the <<codelist-countrycode>> code list.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=Country]
----

== End User/Territory

The element `EndUser/Territory` is optional. 
If it is present, it MUST contain the Territory of the End User's legal address.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=Territory]
----

== End User/Sending Dataset Type

For every unique Dataset Type ID (Document Type ID) this End User has sent in the Reporting Period,
one `EndUser/SendingDatasetTypeID` element MUST be provided.

The `schemeID` attribute MUST contain the scheme identifier of the respective Dataset Type ID.

NOTE: The number of exchanged Datasets is not part of this report, it is part of the Transaction Statistics Report.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=SendingDatasets]
----

== End User/Receiving Dataset Type

For every unique Dataset Type ID (Document Type ID) this End User has received in the Reporting Period,
one `EndUser/ReceivingDatasetTypeID` element MUST be provided.

The `schemeID` attribute MUST contain the scheme identifier of the respective Dataset Type ID.

NOTE: The number of exchanged Datasets is not part of this report, it is part of the Transaction Statistics Report.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=ReceivingDatasets]
----

== End User/Participant ID

For every identifiers used in the Peppol Network by the End User, 
related only to the Peppol Services which that particular Service Providers 
offers to them, one `EndUser/ParticipantID` element MUST be provided.

The `schemeID` attribute MUST contain the scheme identifier of the respective Participant ID.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=ParticipantID]
----

== End User/Intermediary

Where intermediaries are both actively involved in the transmission of the 
End Users’ Peppol Services and hold a contractual relationship with the 
End User as described in the SP Agreement clause 9.2,
the element `EndUser/Intermediary` MUST contain the Intermediary information.

Each End User can have no, one or multiple Intermediaries.

.Example (including the optional Territory):
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=Intermediary]
----

.Example (excluding the optional Territory):
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=Intermediary2]
----

== End User/Intermediary/Legal ID

The element `EndUser/Intermediary/LegalID` MUST contain the Legal Identifier of the Intermediary.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=IntermediaryLegalID]
----


== End User/Intermediary/Legal Name

The element `EndUser/Intermediary/LegalName` MUST contain the Legal Name of the Intermediary.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=IntermediaryLegalName]
----

== End User/Intermediary/Country

The element `EndUser/Intermediary/Country` MUST contain the country code of the Intermediary's legal address only.
The values in this element MUST be part of the <<codelist-countrycode>> code list.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=IntermediaryCountry]
----

== End User/Intermediary/Territory

The element `EndUser/Intermediary/Territory` is optional. 
If it is present, it MUST contain the Territory of the Intermediary's legal address.

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=IntermediaryTerritory]
----
