= CustomizationID

The element `CustomizationID`  Identifies a customization of this format for a specific use.

.Example:
[source, xml, indent=0]
----
include::./snippet//snippet-1.xml[tags=CustomizationID]
----


= Header

The element `Header` contains the reporting periode start date, reporting period end date 
and the Id of the reporting organization.

.Example:
[source, xml, indent=0]
----
include::./snippet//snippet-1.xml[tags=Header]
----


== Report Start Date

The element `ReportPeriodStart` MUST contain the start date (inclusive) of the reporting period.
            Usually the first day of the preceding month.
            E.g. for the first report this may be a different date as well of the reporting period.

.Example:
[source, xml, indent=0]
----
include::./snippet//snippet-1.xml[tags=ReportPeriodStart]
----


== Report end date
The element `ReportPeriodEnd` MUST contain the The last date (inclusive) of the reporting period.
            Usually the last day of the preceding month.

.Example:
[source, xml, indent=0]
----
include::./snippet//snippet-1.xml[tags=eindReportPeriodEnd
----

== Reporter ID
The element `ReporterID` MUST contain The unique identification of the Service Provider that is providing the data.
            If the "schemeID" attribute is set to "CertSubjectCN" than the value must be
              the Peppol AP Certificate Subject CN (Common Name).
              Other scheme IDs are currently not supported

.Example:
[source, xml, indent=0]
----
include::./snippet/snippet-1.xml[tags=ReporterID]
----