name: PDK-Dev

on:
  push:
    branches:
      - Develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login with docker to ECR
        id: login-ecr
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws


      - name: Pull docker image
        run: docker pull public.ecr.aws/openpeppol/pdk:latest

      - name: Prepare PDK
        run: docker run --rm -i -v $(pwd):/src public.ecr.aws/openpeppol/pdk:latest pdk -T

      - name: Run PDK
        run: docker run --rm -i -v $(pwd):/src public.ecr.aws/openpeppol/pdk:latest pdk

      - name: Publish to Test-Docs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            aws s3 sync --acl public-read --region eu-west-1 target/site ${{ secrets.AWS_S3_PATH }}/reporting-bis/${GITHUB_REF#refs/heads/}
